livekitlib: Updated with new code from Tomas-M and crim50n.

diff --git a/livekitlib b/livekitlib
--- a/livekitlib
+++ b/livekitlib
@@ -211,6 +211,11 @@ init_zram()
    fi
 }
 
+aufs_is_supported()
+{
+   cat /proc/filesystems | grep aufs
+}
+
 # load the AUFS kernel driver. If not found,
 # load overlayfs instead.
 #
@@ -309,6 +314,7 @@ mounted_dir()
    done
 }
 
+
 # Initialize blkid cache by manually probing all devices
 #
 init_blkid_cache()
@@ -394,7 +400,7 @@ mount_command()
 network_device()
 {
    debug_log "network_device" "$*"
-   cat /proc/net/dev | grep : | grep -v lo: | cut -d : -f 1 | tr -d " " | head -n 1
+   cat /proc/net/dev | grep : | grep -v lo: | grep -v ip6tnl | cut -d : -f 1 | tr -d " " | head -n 1
 }
 
 
@@ -563,6 +569,18 @@ find_data_try()
    mkdir -p "$1"
    blkid | sort | cut -d: -f 1 | grep -E -v "/loop|/ram|/zram" | while read DEVICE; do
       FROM="$2"
+
+      # supported syntax is even like from=/dev/sr0/livekitname. It is not so much
+      # optiomal to put the following block of code here inside the while loop,
+      # but there is no harm so lets modify DEVICE and FROM to make it work
+      if echo "$FROM" | grep -q '^/dev/'; then
+         DEVICE="$(echo "$FROM" | cut -d '/' -f 1-3)"
+         FROM="$(echo "$FROM" | cut -d '/' -f 4-)"
+         if [ "$FROM" = "" ]; then
+            FROM="$LIVEKITNAME"
+         fi
+      fi
+
       FS="$(device_bestfs "$DEVICE")"
       OPTIONS="$(fs_options $FS)"
       MOUNT="$(mount_command $FS)"
@@ -579,6 +597,15 @@ find_data_try()
       # search for bundles in the mounted directory
       if [ "$(find "$1/$FROM" -maxdepth 1 -name "*.$BEXT" 2>/dev/null)" != "" ]; then
          # we found at least one bundle/module here
+         echo "$FROM" > /var/log/from.log
+         echo "$1/$FROM" | tr -s "/" | sed -r "s:/[^/]+/[.][.]/:/:g"
+         return
+      fi
+
+      # search for bundles in modules directory
+      if [ "$(find "$1/$FROM" -maxdepth 1 -name "*.$BOEXT" 2>/dev/null)" != "" ]; then
+         # we found at least one bundle/module here
+         echo "$FROM" > /var/log/from.log
          echo "$1/$FROM" | tr -s "/" | sed -r "s:/[^/]+/[.][.]/:/:g"
          return
       fi
@@ -586,9 +613,11 @@ find_data_try()
       # search for bundles in the mounted directory
       if [ "$(find "$1/$FROM" -maxdepth 1 -name "*.$DFBEXT" 2>/dev/null)" != "" ]; then
          # we found at least one bundle/module here
+         echo "$FROM" > /var/log/from.log
          echo "$1/$FROM" | tr -s "/" | sed -r "s:/[^/]+/[.][.]/:/:g"
          return
       fi
+
       # unmount twice, since there could be mounted ISO as loop too. If not, it doesn't hurt
       umount "$1" 2>/dev/null
       umount "$1" 2>/dev/null
@@ -605,7 +634,7 @@ find_data()
 {
    debug_log "find_data" "$*"
 
-   local DATA FROM
+   local DATA FROM TIMEOUT ASKPID DIR
 
    FROM="$(cmdline_value from)"
 
@@ -621,11 +650,43 @@ find_data()
       return
    fi
 
+   # If user wants to get asked, ask and periodically update list of devices
+   if echo "$FROM" | grep -q '^ask'; then
+      (while true; do
+         # Among other things, filter out swap, since the user may have a hard disk with a swap partition on the actual hardware.
+         blkid -o full -s TYPE -s LABEL | grep -E -v "/loop|/ram|/zram|TYPE=\"swap\"" | while read -r LINE; do
+            PARTITION=$(echo "$LINE" | awk '{print $1}' | awk -F':' '{print $1}')
+            SIZE=$(fdisk -l "$PARTITION" 2>/dev/null | head -n 1 | awk '/Disk \// {print $3, $4}' | tr -d ",")
+            TYPE=$(echo $LINE | awk -F'TYPE="' '{print $2}' | awk -F'"' '{print $1}')
+            LABEL=$(echo $LINE | awk -F'LABEL="' '{print $2}' | awk -F'"' '{print $1}')
+            echo "$PARTITION: SIZE=\"$SIZE\" TYPE=\"$TYPE\" LABEL=\"$LABEL\" "
+         done >/tmp/0.txt
+         mv -f /tmp/0.txt /tmp/ask.txt
+         sleep 1
+      done) &
+      ASKPID=$!
+      sleep 1 # give blkid some chance to finish
+      if echo "$FROM" | grep -q '^ask/'; then
+         DIR="$(echo "$FROM" | cut -d '/' -f 2-)"
+      else
+         DIR="$LIVEKITNAME"
+      fi
+      DEVICE="$(ncurses-menu -t "Look for /$DIR/ directory on:" -f /tmp/ask.txt -s 2>&1 >/dev/tty1 </dev/tty1)"
+      DEVICE="$(echo "$DEVICE" | cut -d : -f 1)"
+      if echo "$FROM" | grep -q '^ask/'; then
+         FROM="$DEVICE/$(echo "$FROM" | cut -d '/' -f 2-)"
+      else
+         FROM="$DEVICE"
+      fi
+      kill $ASKPID
+   fi
+
+   # default to livekitname autodetected on all disks
    if [ "$FROM" = "" ]; then FROM="$LIVEKITNAME"; fi
 
    echo_green_star >&2
    echo -n "Looking for $LIVEKITNAME data in /$FROM .." | tr -s "/" >&2
-   for timeout in $(seq 1 $1); do
+   for TIMEOUT in $(seq 1 $1); do
       echo -n "." >&2
       refresh_devs
       DATA="$(find_data_try "$2" "$FROM")"
@@ -652,6 +713,118 @@ check_data_found()
 }
 
 
+# Get a human readable format of time elapsed since given datetime
+# $1 = date time
+#
+date_diff_since_now()
+{
+   local NOW TIMESTAMP SEC MINS HOURS DAYS
+
+   NOW=$(date '+%s')
+   TIMESTAMP=$(date --date "$1" '+%s')
+   SEC=$(($NOW - $TIMESTAMP))
+   MINS=$(($SEC / 60))
+   HOURS=$(($SEC / 3600))
+   DAYS=$(($SEC / 86400))
+
+   if [ "$DAYS" -gt 0 ]; then echo "$DAYS days" | sed -r "s/^1 days/1 day/";
+   elif [ "$HOURS" -gt 0 ]; then echo "$HOURS hours" | sed -r "s/^1 hours/1 hour/";
+   elif [ "$MINS" -gt 0 ]; then echo "$MINS minutes" | sed -r "s/^1 minutes/1 minute/";
+   else echo "$SEC seconds" | sed -r "s/^1 seconds/1 second/";
+   fi
+}
+
+
+# Restore persistent changes from previous session.
+# Store persistent changes to a directory and keep the directory in a session file,
+# so we know which session was active last time so we can resume it next time
+# $1 = changes directory
+#
+restore_perch_session()
+{
+   debug_log "restore_perch_session" "$*"
+
+   local TIMEOUT DEVICE FS OPTIONS MOUNT
+   local CHANDIR PERCHDIR FILE LAST LASTMOD LASTSESSION NEW DIR USAGE LAST DAYS
+
+   CHANDIR="$1"
+   PERCHDIR="$(cmdline_value perchdir)"
+
+   # Supported syntax is even like perchdir=/dev/sda1/changes
+   # In this case, perchdir is mounted over $CHANDIR and is set to ask
+   if echo "$PERCHDIR" | grep -q '^/dev/'; then
+      DEVICE="$(echo "$PERCHDIR" | cut -d '/' -f 1-3)"
+      PERCHDIR="$(echo "$PERCHDIR" | cut -d '/' -f 4-)"
+
+      FS="$(device_bestfs "$DEVICE")"
+      OPTIONS="$(fs_options $FS)"
+      MOUNT="$(mount_command $FS)"
+
+      echo -n "* Waiting for persistent changes on $DEVICE .." >&2
+      for TIMEOUT in $(seq 1 20); do
+         echo -n "." >&2
+         refresh_devs
+         $MOUNT "$DEVICE" "$CHANDIR" $OPTIONS 2>/dev/null
+         if [ $? -eq 0 ]; then
+            if [ "$PERCHDIR" != "" -a "$PERCHDIR" != "/" ]; then
+               mkdir -p "$CHANDIR/$PERCHDIR"
+               $MOUNT --bind "$CHANDIR/$PERCHDIR" "$CHANDIR"
+               if [ $? -eq 0 ]; then
+                 echo -e "\n" >&2
+                 PERCHDIR=ask
+                 break
+               fi
+            else
+              echo -e "\n" >&2
+               PERCHDIR=ask
+               break
+            fi
+         fi
+         sleep 1
+      done
+   fi
+
+   LAST=last_session.txt
+   LASTSESSION=$(cat "$CHANDIR/$LAST" 2>/dev/null)
+
+   # ask for session, print msgs to stderr so it is visible
+   if [ "$LASTSESSION" != "" -a "$PERCHDIR" = "ask" ]; then
+      ls -1 $CHANDIR | grep -E "^[0-9]+" | while read DIR; do
+         USAGE=$(du -s -h "$CHANDIR/$DIR" 2>/dev/null | sed -r "s/[[:space:]].*//")
+         LASTMOD="$(date -r "$CHANDIR/$DIR" "+%Y-%m-%d %H:%M:%S")"
+         DAYS=$(date_diff_since_now "$LASTMOD")
+         echo "$LASTMOD Resume session #$DIR - last access $DAYS ago - using $USAGE" | sed -r "s/(.)\$/ \\1B/"
+      done | sort -r | cut -d " " -f 3- > /tmp/sessions.txt
+
+      PERCHDIR="$(ncurses-menu -t 'Select action:' -o 'Start a new session' -f /tmp/sessions.txt 2>&1 >/dev/tty1 < /dev/tty1)"
+
+      if echo "$PERCHDIR" | grep -q "new"; then
+         PERCHDIR="new"
+      else
+         PERCHDIR="$(echo "$PERCHDIR" | sed -r 's/.*#//' | sed -r 's/[^0-9].*//')"
+      fi
+   fi
+
+   # restore name for previous session if empty
+   if [ "$PERCHDIR" = "" -o "$PERCHDIR" = "resume" ]; then
+      PERCHDIR="$LASTSESSION"
+   fi
+
+   # if last is empty or new/nonexistent is requested, create new
+   if [ "$PERCHDIR" = "" -o "$PERCHDIR" = "new" -o ! -d "$CHANDIR/$PERCHDIR" ]; then
+      NEW="$(ls -1 $CHANDIR | egrep '^[0-9]' | sed -r 's/[^0-9].*//' | sort | tail -n 1)"
+      NEW=$(($NEW + 1))
+      mkdir -p "$CHANDIR/$NEW"
+      PERCHDIR="$NEW"
+   fi
+
+   # remember current, update timestamp
+   echo "$PERCHDIR" > "$CHANDIR/$LAST"
+   touch "$CHANDIR/$PERCHDIR"
+   echo "$PERCHDIR"
+}
+
+
 # Activate persistent changes
 # $1 = data directory
 # $2 = target changes directory
@@ -660,9 +833,10 @@ persistent_changes()
 {
    debug_log "persistent_changes" "$*"
 
-   local CHANGES T1 T2 EXISTS
+   local CHANGES T1 T2 EXISTS DEVICE PERCHDIR PERCHSIZE PERCHFILE GROWDIR
 
    CHANGES="$1/$(basename "$2")"
+   DEVICE="$(df $1 | tail -n 1 | cut -d " " -f 1)"
    T1="$CHANGES/.empty"
    T2="$T1"2
 
@@ -670,9 +844,12 @@ persistent_changes()
    mkdir -p "$2"
 
    # If persistent changes are not requested, end here
+   # so memory will be used to save chanves temporarily
    if grep -vq perch /proc/cmdline; then
       return
    fi
+
+   PERCHDIR=$(restore_perch_session "$CHANGES")
 
    # check if changes directory exists and is writable
    touch "$T1" 2>/dev/null && rm -f "$T1" 2>/dev/null
@@ -683,6 +860,7 @@ persistent_changes()
       return
    fi
 
+   # try to use native fs if posix-compatible
    echo_green_star
    echo "Testing persistent changes for posix compatibility"
    touch "$T1" && ln -sf "$T1" "$T2" 2>/dev/null && \
@@ -691,28 +869,61 @@ persistent_changes()
    rm "$T1" "$T2" 2>/dev/null
 
    if [ $? -eq 0 ]; then
-      echo "* Activating native persistent changes"
-      mount --bind "$CHANGES" "$2"
-      return
+      if device_bestfs $DEVICE | grep -v ntfs >/dev/null; then
+         echo "* Activating native persistent changes for session #$PERCHDIR"
+         mount --bind "$CHANGES/$PERCHDIR" "$2"
+         return
+      fi
+   else
+      # if test failed at any point, we may have temp files left behind
+      rm "$T1" "$T2" 2>/dev/null
    fi
 
-   if [ -e "$CHANGES/changes.dat.0" ]; then
-      echo "* Restoring persistent changes"
+
+   # If we are here, native fs was not supported or user requested perchsize anyway
+
+   PERCHSIZE=$(cmdline_value perchsize | sed -r "s/TB?/000000/i" | sed -r "s/GB?/000/i" | sed -r "s/[^0-9]//g")
+
+   if [ "$PERCHSIZE" = "" ]; then
+      PERCHSIZE=16000
+   fi
+
+   # minimum size is 16GB
+   if [ "$PERCHSIZE" -lt 16000 ]; then
+      PERCHSIZE=16000
+   fi
+
+   PERCHFILE="$PERCHDIR/changes.dat"
+
+   # resume or use new
+   if [ -e "$CHANGES/$PERCHFILE" ]; then
+      echo "* Resuming persistent changes for session #$PERCHDIR"
       EXISTS="true"
    else
-      echo "* Creating new persistent changes"
+      echo "* Creating new persistent changes for session #$PERCHDIR"
       EXISTS=""
    fi
 
-   @mount.dynfilefs -f "$CHANGES/changes.dat" -s 16000 -m "$2" -p 4000
+   # mount it, splitsize of 4000MB is hardcoded, it must be the same all the time anyway
+   echo "- mounting dynamically enlarged storage"
+   @mount.dynfilefs -f "$CHANGES/$PERCHFILE" -s $PERCHSIZE -m "$2" -p 4000
    if [ ! "$EXISTS" ]; then
-      mke2fs -F "$2/virtual.dat" >/dev/null 2>&1
+      echo "- creating filesystem"
+      mkfs.xfs.custom "$2/virtual.dat"
    fi
-   mount -o loop,sync "$2/virtual.dat" "$2"
 
-   # if test failed at any point, we may have temp files left behind
-   rm "$T1" "$T2" 2>/dev/null
-   rmdir "$2/lost+found" 2>/dev/null
+   if [ "$PERCHSIZE" -gt 16000 ]; then
+      GROWDIR=/tmp/changes.grow
+      echo "- grow if needed"
+      mkdir -p "$GROWDIR"
+      mount -o loop "$2/virtual.dat" "$GROWDIR"
+      xfs_growfs "$GROWDIR" >/dev/null
+      umount "$GROWDIR"
+      rmdir "$GROWDIR"
+   fi
+
+   echo "- mounting persistent changes"
+   mount -o loop "$2/virtual.dat" "$2"
 }
 
 
@@ -784,6 +995,7 @@ filter_noload()
 {
    local FILTER
    FILTER=$(cmdline_value noload)
+   FILTER=${FILTER//,/|}
    if [ "$FILTER" = "" ]; then
       cat -
    else
@@ -879,7 +1091,7 @@ union_append_bundles()
       echo_green_star
       echo "Adding bundles to union"
       find "$1" -mindepth 1 -maxdepth 1 | sortmod | while read BUNDLE; do
-         mount -o remount,add:1:"$BUNDLE" aufs "$2"
+         mount -o remount,add:1:"$BUNDLE=rr+wh" aufs "$2"
       done
    fi
 }
