Update init and livekitlib to have overlayfs option. Thanks to johndah4x0r for overlayfs code in his livekit-improved project.

diff --git a/livekitlib b/livekitlib
--- a/livekitlib
+++ b/livekitlib
@@ -118,7 +118,7 @@ create_bundle()
 {
    debug_log "create_module" "$*"
    rm -f "$2" # overwrite, never append to existing file
-   mksquashfs "$1" "$2" -comp xz -b 1024K -always-use-fragments $3 $4 $5 $6 $7 $8 $9>/dev/null
+   mksquashfs "$1" "$2" -comp xz -b 512K $3 $4 $5 $6 $7 $8 $9>/dev/null
 }
 
 
@@ -140,6 +140,68 @@ transfer_initramfs()
    fi
 }
 
+# Get / generate lowerdirs argument for 'mount -t overlayfs'
+# $1: Bundle mountpoint directory "/memory/bundles"
+# $2: Bundle extension
+#
+get_lowerdirs()
+{
+    local BUND_DIRS BUND_EXT BUND MNT_OPT
+    BUND_DIRS="$1"
+    BUND_EXT="$2"
+    MNT_OPT=""
+
+    find "$BUND_DIRS" -maxdepth 1 -type d -name "*.${BUND_EXT}" | sort | {
+        while read -r BUND; do
+            MNT_OPT="${BUND}:${MNT_OPT}"
+        done
+        MNT_OPT="${MNT_OPT%?}"
+        echo "$MNT_OPT"
+    }
+}
+
+# Check for POSIX compatiblity
+# WILL replace the built-in check inside persistent_changes()
+# $1: Directory to test
+#
+# Return codes:
+# 0 - Success
+# 1 - General error
+# 2 - Inaccessable
+#
+posix_chk() {
+    local CWD F1 F2 TARGET
+
+    TARGET="$(realpath "$1")"
+    CWD="$(pwd)"
+    F1="${TARGET}/.file1"
+    F2="${TARGET}/.file2"
+
+    # Check if read-only or inaccessable
+    touch "$F1" 2>/dev/null && [ -e "$F1" ]
+
+    if [ $? -ne 0 ]; then
+        cd "$CWD"
+        return 2
+    fi
+
+    # Start the cruel proccess.
+    # FAT32 hates, and really hates linking files!
+    chmod +x "$F1" 2>/dev/null && [ -x "$F1" ] && \
+    chmod -x "$F1" 2>/dev/null && [ ! -x "$F1" ] && \
+    ln -s "$F1" "$F2" 2>/dev/null && [ -e "$F2" ] && \
+    rm -f "$F1" "$F2" 2>/dev/null
+
+    if [ $? -ne 0 ]; then
+        cd "$CWD"
+        rm "$F1"
+        return 1
+    else
+        rm "$F1" "$F2"
+        cd "$CWD"
+        return 0
+    fi
+}
 
 # mount virtual filesystems like proc etc
 #
@@ -166,7 +228,7 @@ modprobe_everything()
    echo_green_star >&2
    echo "Probing for hardware" >&2
 
-   find /lib/modules/ | fgrep .ko | egrep $1 $2 | sed -r "s:^.*/|[.]ko\$::g" | xargs -n 1 modprobe 2>/dev/null
+   find /lib/modules/ | sort | fgrep .ko | egrep $1 $2 | sed -r "s:^.*/|[.]ko\$::g" | xargs -n 1 modprobe 2>/dev/null
    refresh_devs
 }
 
@@ -222,6 +284,25 @@ init_aufs()
    refresh_devs
 }
 
+# Load OverlayFS kernel module
+#
+modprobe_overlay()
+{
+    debug_log "modprobe_overlay" "$*"
+
+    # Prepare for error messages
+    echo >>/var/log/livkedbg
+
+    modprobe overlay 2>>/var/log/livedbd
+
+    # If overlay module failed to load, stop init
+    if [ $? -ne 0 ]; then
+        fatal "Failed to load OverlayFS module!"
+    fi
+
+    # finally, refresh all devices
+    refresh_devs
+}
 
 # Setup empty union
 # $1 = changes directory (ramfs or persistent changes)
@@ -465,7 +546,7 @@ download_data_pxe()
 
       init_network_ip
 
-      echo "* Downloading PXE file list" >&2
+      echo "* Downloading PXE file list"
 
       PROTOCOL=http
       wget -q -O "$1/PXEFILELIST" "http://$SERVER:$PORT/PXEFILELIST?$(uname -r):$(uname -m)"
@@ -475,7 +556,7 @@ download_data_pxe()
          tftp -g -r PXEFILELIST -l "$1/PXEFILELIST" $SERVER
       fi
 
-      echo "* Downloading files from the list" >&2
+      echo "* Downloading files from the list"
 
       cat "$1/PXEFILELIST" | while read FILE; do
          if [ "$PROTOCOL" = "http" ]; then
@@ -734,6 +815,72 @@ sortmod()
    cat - | sed -r "s,(.*/(.*)),\\2:\\1," | sort -n | cut -d : -f 2-
 }
 
+# Mount squashfs filesystem bundles
+# and add them to union
+# NEW: Prepare Overlay file system
+# $1 = directory where to search for bundles
+# $2 = directory where to mount bundles
+# $3 = directory where the changes is
+# $4 = directory where union is supposed to be
+#
+prepare_overlay()
+{
+    debug_log "prepare_overlay" "$*"
+
+    local BUN ALL_BUNDS LOWERDIR CHANGEDIR UPPERDIR WORKDIR
+
+	echo_green_star
+    echo "Preparing OverlayFS union..." >&2
+
+    echo >>/var/log/livedbg
+
+    # Just tell me why! Why be compact?!?
+    ( ls -1 "$1" | sort -n ; cd "$1" ; find modules/ 2>/dev/null | \
+    sortmod | filter_load) | grep '[.]'"$BEXT"'$' |\
+    filter_noload | \
+    while read -r BUNDLE; do
+        BUN="$(basename "$BUNDLE")"
+        echo "Mounting $BUN to /memory/bundles..." >&2
+        mkdir -p "$2/$BUN"
+
+        # It now depends on your kernel!
+        mount -o loop -t squashfs "$1/$BUNDLE" "$2/$BUN"
+    done
+
+    # Time to mount overlayfs union
+    ALL_BUNDS="$(get_lowerdirs "$2" "$BEXT")"
+    LOWERDIR="/memory/lowerdir"
+    CHANGEDIR="$3"
+    UPPERDIR="${CHANGEDIR}/.rootfs"
+    WORKDIR="${CHANGEDIR}/.work"
+
+    # Make the both the upperdir and workdir ('cuz it's non-existant, yet...)
+    mkdir "$UPPERDIR" >/dev/null 2>&1
+    mkdir "$WORKDIR" >/dev/null 2>&1
+
+    # Make the union directory (this might actually be an alarming bug)
+    mkdir "$4" >/dev/null 2>&1
+
+    # Separate commands (to avoid `sh' errors)
+    # Join all modules together into the 'lowerdir' of main overlay
+    mkdir "$LOWERDIR" >/dev/null 2>&1
+    mount -t overlay -o lowerdir="$ALL_BUNDS" overlay "$LOWERDIR" \
+        >>/var/log/livedbg 2>&1
+
+    if [ $? -ne 0 ]; then
+        fatal "Failed to mount lower directory of main OverlayFS union!"
+    fi
+
+    # Join 'lowerdir' with the save directory (upperdir,workdir)
+    mount -t overlay -o lowerdir="$LOWERDIR",upperdir="$UPPERDIR",workdir="$WORKDIR" \
+    overlay "$4" >>/var/log/livedbg 2>&1
+
+    # Check if we got any errors...
+    if [ $? -ne 0 ]; then
+        fatal "Failed to mount main OverlayFS union!"
+    fi
+
+}
 
 # Mount squashfs filesystem bundles
 # and add them to union
@@ -789,7 +936,7 @@ fstab_create()
       LABEL="$(basename $DEVICE)"
       OPTS="defaults,noatime,nofail,x-systemd.device-timeout=10"
 
-      if [ "$FS" != "" -a "$FS" != "swap" -a "$FS" != "squashfs" -a "$DEVICE" != "$BOOTDEVICE" ]; then
+      if [ "$FS" != "swap" -a "$FS" != "squashfs" -a "$DEVICE" != "$BOOTDEVICE" ]; then
          mkdir -p "$1/media/$LABEL"
          echo "$DEVICE" "/media/$LABEL" $FS $OPTS 0 0 >> $FSTAB
       fi
@@ -842,7 +989,7 @@ change_root()
    mkdir -p run
    mount -t tmpfs tmpfs run
    mkdir -p run/initramfs
-   mount -n -o remount,ro aufs .
+   #mount -n -o remount,ro aufs .
    pivot_root . run/initramfs
    exec $CHROOT . $INIT < dev/console > dev/console 2>&1
 }
